name: rl_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - pip
  - pip:
    - keras==2.15.0
    - matplotlib==3.8.2
    - numpy==1.26.3
    - tensorflow==2.15.0
    - ipykernel==6.29.3